server:
  port: 8071

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shop?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
  flyway:
    # 启用flyway
    enabled: true
    # 存放sql脚本的路径
    locations: classpath:db/migration
    # sql脚本执行版本控制表，元信息
    table: flyway_schema_history
    baseline-on-migrate: true
    baseline-version: 1
    encoding: UTF-8
    out-of-order: true
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    prefix:
      classpath: /templates
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
#  profiles:
#    active: dev
  servlet:
    multipart:
      max-file-size: 30
      max-request-size: 30


logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            logging: info
    root: info
    com.relyy.shop: info

mybatis-plus:
  type-aliases-package:
  configuration-properties:
    map-underscore-to-camel-case: true
  mapper-locations: mapper/*Mapper.xml
