CREATE TABLE `TB_USER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `USERID` int(10) unsigned NOT NULL COMMENT '用户id',
  `USERNAME` varchar(255) DEFAULT NULL COMMENT '真实姓名',
  `NICKNAME` varchar(255) NOT NULL COMMENT '用户名',
  `PHONENUM` varchar(20) DEFAULT NULL COMMENT '手机号码',
  `EMAIL` varchar(40) DEFAULT NULL COMMENT '邮箱',
  `TELPHONE` varchar(20) DEFAULT NULL COMMENT '电话号码',
  `ADDRESS` varchar(255) DEFAULT NULL COMMENT '用户地址',
  `STATUS` tinyint(2) DEFAULT '1' COMMENT '用户状态',
  `STAGE` varchar(10) DEFAULT '' COMMENT '用户状态',
  `ACTIVE_CODE` varchar(255) DEFAULT NULL COMMENT '激活码',
  `CREATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  `IS_DELETE` int(2) DEFAULT '0' COMMENT '用户删除状态',
  `HEADIMG` varchar(255) DEFAULT NULL COMMENT '用户头像',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `TB_HEAD_CLASSIFY` (
  `CLASSIFY_ID` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '一级分类ID',
  `CLASSIFY_NAME` varchar(255) DEFAULT NULL COMMENT '一级分类名',
  `CREATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `IS_DELETE` int(11) DEFAULT '0' COMMENT '是否删除',
  PRIMARY KEY (`CLASSIFY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `TB_CATEGORY` (
  `CLASSIFY_ID` int(11) NOT NULL COMMENT '二级分类id',
  `CLASSIFY_NAME` varchar(255) NOT NULL COMMENT '二级分类名',
  `PARENT_ID` int(11) DEFAULT NULL COMMENT '一级分类ID',
  `CREATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `IS_DELETE` int(4) DEFAULT NULL,
  PRIMARY KEY (`CLASSIFY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `TB_COMMODITY` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '商品ID',
  `COMMODITY` varchar(255) DEFAULT NULL COMMENT '商品名称',
  `SHOPPRICE` decimal(10,2) DEFAULT NULL COMMENT '商品价格',
  `MARKETPRICE` decimal(10,2) DEFAULT NULL COMMENT '市场价格',
  `DESCRIPTE` varchar(255) DEFAULT NULL COMMENT '商品描述',
  `COMMODITY_IMG` varchar(255) DEFAULT NULL COMMENT '商品图片',
  `QUNANTITY` int(255) DEFAULT NULL,
  `CLASSIFY_ID` int(11) DEFAULT NULL COMMENT '商品二级分类ID',
  `CREATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `IS_DELETE` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `TB_CONSIGNEEINFO` (
  `ID` int(11) NOT NULL,
  `CONSIGNEEID` int(11) NOT NULL COMMENT '收货人ID',
  `USERID` int(11) NOT NULL COMMENT '用户id',
  `CONSIGNEE_NAME` varchar(255) NOT NULL COMMENT '收货人名字',
  `CONSIGNEE_ADDRESS` varchar(255) NOT NULL COMMENT '收货人地址',
  `CONSIGNEE_PHONE` varchar(13) NOT NULL COMMENT '收货人手机号码',
  `CONSIGNEE_TEL` varchar(255) DEFAULT NULL COMMENT '收货人电话号码',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT '修改时间',
  `STATUS` int(4) DEFAULT '0' COMMENT '收货人状态'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `TB_ORDERED_CATEGORYLIST` (
  `ID` int(11) NOT NULL,
  `ORDERID` int(11) DEFAULT NULL COMMENT '订单编号',
  `COMMODITYID` int(11) DEFAULT NULL COMMENT '商品编号',
  `COMMODITY_QUANTITY` int(11) DEFAULT NULL COMMENT '购买商品数量',
  `COMMODITY_PRICE` decimal(10,2) DEFAULT NULL COMMENT '商品价格',
  `DISCOUNTS_TYPE` int(11) DEFAULT '0' COMMENT '优惠类型',
  `SUBTOTAL` decimal(10,0) DEFAULT NULL COMMENT '价格小计',
  `CREATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `STATU` int(2) DEFAULT '0' COMMENT '状态',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `TB_ORDERINFO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ORDERID` int(11) NOT NULL COMMENT '订单编号',
  `ORDER_PRICE` decimal(10,2) NOT NULL COMMENT '订单金额',
  `ORDER_STATUS` int(4) DEFAULT '1' COMMENT '订单状态',
  `CONSIGNEEID` int(11) NOT NULL COMMENT '收货人ID',
  `CREATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '订单创建时间',
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT '订单修改时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

